FROM ubuntu:14.04
MAINTAINER Michele Bologna <michele.bologna@gmail.com>

RUN apt-get update && \
	apt-get install -qqy wget supervisor && \
	wget -O - https://repo.saltstack.com/apt/ubuntu/ubuntu14/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add - && \
	echo "deb http://repo.saltstack.com/apt/ubuntu/ubuntu14/latest trusty main" >> /etc/apt/sources.list && \
	apt-get update && \
	apt-get install -qqy salt-master salt-api && \
	useradd saltdev -p '$6$0BIlOqYqg5Rcuu5A$ojdWZ.aZztdSqPCnqsEE3ViRDcFAZ0MSp0UUvT23GG5mnbUOcalZPh8basKox2wcn4F1if2kfChOO/J1K2boe.' && \
    apt-get clean && \
    rm -fr /var/lib/apt/lists/*

COPY etc_master/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
VOLUME ["/etc/salt"]
EXPOSE 8000
CMD ["/usr/bin/supervisord"]