name: Build and test

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      salt-master:
        image: mbologna/saltstack-master
        options: --name saltmaster
        ports:
          - 8000:9080
      salt-minion1:
        image: mbologna/saltstack-minion
        options: --name saltminion1 --link saltmaster:salt
      salt-minion2:
        image: mbologna/saltstack-minion
        options: --name saltminion2 --link saltmaster:salt

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Set up JDK 11
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build and test with Maven
        run: mvn checkstyle:check javadoc:javadoc test package
      - name: Get branch name or tag
        if: success()
        uses: tj-actions/branch-names@dde14ac574a8b9b1cedc59a1cf312788af43d8d8 # v8.2.1
        id: branch-name
      - name: Publish javadoc for the default branch
        if: success() && steps.branch-name.outputs.is_default == 'true'
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/apidocs
          destination_dir: docs/${{ steps.branch-name.outputs.current_branch }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
      - name: Publish javadoc for a tagged release
        if: success() && steps.branch-name.outputs.is_tag == 'true'
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/apidocs
          destination_dir: docs/${{ steps.branch-name.outputs.tag }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
      - name: Create tagged release
        if: success() && steps.branch-name.outputs.is_tag == 'true'
        uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            target/salt-netapi-client*.jar
